Added handling for empty or None sample_names
bokulich-lab/q2-assembly pull request #50
Opened 2023-07-24 08:55 UTC by ChristosMatzoros

When the user does not provide anything for the sample-names option from the command line, the function is called without providing a value for sample_names and the sample_names variable will default to None. When we attempt to evaluate len(set(sample_names)), Python tries to create a set from sample_names, but since sample_names is None, it cannot create a set from a None object, hence the "NoneType object is not iterable" error. In case of an empty list we can add an element called "sample" as the default sample name and avoid that error.

2023-07-24 14:42 UTC, misialq commented
Hey @ChristosMatzoros,
Thanks for submitting your PR! I have two small comments here, for now:
- if you are setting the value of "sample_name" to a fixed value, maybe you could also display a warning to the user saying that that's what is happening? this will effectively create only one sample so it would be good to let the user know
- could you also include a unit test to address the bug and the solution you are proposing?

Thanks!

2023-07-31 16:21 UTC, ChristosMatzoros commented
Hi @misialq,

I've made some updates. In verbose mode, I added a warning that addresses the situation when the --sample-names option is not given. Additionally, I included a new unit test in test_iss.py that calls the generate_reads() function without providing the --sample-names option. This test should fail in the previous version but execute successfully in the new version of the code. However, it might need some changes in the formatting of the code.

Thank you!

2023-10-05 07:00 UTC, misialq commented
Hey @ChristosMatzoros, could you please rebase/merge the `main` branch? That should hopefully fix the CI :)

2023-10-10 12:35 UTC, misialq requested changes
Hey @ChristosMatzoros, while your test passes, there are a few things which you should do slightly differently here:
- your test runs the actual `iss` tool underneath - that should not happen. You should mock the call to `subprocess.run` - you can see how that is done in any other submodule of this plugin
- you should add some assertions to the test - if you mock the call mentioned above, you can then make sure that `iss` was called with the expected parameters (one of them being the sample name you added).

Once you change/add those, feel free to re-request another review :)

2023-10-20 07:08 UTC, misialq approved these changes
Looks good @ChristosMatzoros, thanks! I'll merge that one :)

2023-10-20 07:08 UTC, misialq commented on q2_assembly/iss/tests/test_iss.py
> +        self.assertEqual(result, ["sample"])
```suggestion
        self.assertListEqual(result, ["sample"])
```

2023-10-20 07:08 UTC, misialq commented on q2_assembly/iss/tests/test_iss.py
> +        self.assertEqual(result, ["sample1", "sample2"])
```suggestion
        self.assertListEqual(result, ["sample1", "sample2"])
```

2023-11-03 12:26 UTC, merged