Issue 42
bokulich-lab/q2-assembly pull request #54
Opened 2023-10-06 14:23 UTC by Sann5

Closes #42: "expose additional visualizations generated by QUAST in the evaluate-contigs visualization"

- Adds a button in the QC Report tab which downloads additional reports.
- Adds a tab showing the Krona plots with a drop-down menu to choose between samples and summary. It also deletes the hyperlinks previously available in the QC Report tabb to visualize the Krona plots.

2023-10-06 15:21 UTC, Sann5 commented
### TODO 🗒️

- [ ] Add test for new functions
   - [`_zip_additional_reports`](https://github.com/Sann5/q2-assembly/blob/83ab8946daaf26758489563d5f0d4efd72731fae/q2_assembly/quast/quast.py#L269)
   - [`_zip_dir`](https://github.com/Sann5/q2-assembly/blob/83ab8946daaf26758489563d5f0d4efd72731fae/q2_assembly/quast/quast.py#L196)
   - [`_zip_additional_reports`](https://github.com/Sann5/q2-assembly/blob/83ab8946daaf26758489563d5f0d4efd72731fae/q2_assembly/quast/quast.py#L204)

2023-10-18 08:21 UTC, misialq requested changes
Hey @Sann5, looks great! I tried the viz and all looks as expected - thanks! 🥇 Just one comment below.

2023-10-18 08:21 UTC, misialq commented on q2_assembly/quast/tests/test_quast.py
> +                os.makedirs(file)
Please just directly create all those files in the `tests/data` directory - no need for another function. They will be empty anyways so no space waste and they will simplify the code greatly.

2023-11-03 10:31 UTC, misialq commented on setup.py
> +            "data/zip_test_data/expected/folder_2/subfolder_2/subsubfolder_2/*",
You could replace it with (you'll only really know if it worked properly after the CI is finished):
```suggestion
            "data/zip_test_data/expected/*",
            "data/zip_test_data/expected/*/*",
            "data/zip_test_data/expected/*/*/*",
            "data/zip_test_data/expected/*/*/*/*",
```

2023-11-03 14:24 UTC, merged